import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ReactLenis } from "lenis/react";
import Providers from "./providers";
import Preloader from "@/components/preloader/preloader";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={cn("antialiased", inter.variable)}
      >
        <Providers>
          <Preloader />
          <ReactLenis root>{children}</ReactLenis>
        </Providers>
      </body>
    </html>
  );
}
